import '~/styles/globals.css';

import { GeistSans } from 'geist/font/sans';
import { type Metadata } from 'next';

import { TRPCReactProvider } from '~/trpc/react';
import { AccountButtonHeader } from '~/app/_components/account-button-header';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en' className={`${GeistSans.variable} `}>
      <body className='dark'>
        <header className='flex justify-between px-2 container w-full py-2 mx-auto'>
          <h1 className='font-black text-2xl'>
            STREAM.<span className='text-primary'>IO</span>
          </h1>
          <AccountButtonHeader />
        </header>

        <main className='container px-2 mx-auto'>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </main>
      </body>
    </html>
  );
}
